# -*- coding: utf-8 -*-
"""Lab1_NguyenTrungKien_2001240223.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJB0z7xI6QfQuA1V9xBZ_BP_aaSb7xoJ

Bài 1
"""

a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
tong = a + b
hieu = a - b
thuong = a * b
print("Tổng là: ", tong)
print("Hiệu là: ", hieu)
print("Thương là: ", thuong)

"""Bài 2"""

helloworld = "Hello World"
llo = helloworld[2:5]
print(llo)

"""Bài 3"""

helloworld = " Hello World "
helloworld = helloworld.strip()
helloworld = helloworld.replace('H', 'J')
print(helloworld)

"""Bài 4 - Bài 10"""

a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

if (a > b):
  print('Yes')
else:
  print('No')

if (a == b):
  print(1)
elif (a > b):
  print(2)
else:
  print(3)

d = float(input("Nhập d: "))
if (a == b and b == d):
  print("Hello World!")
c = float(input("Nhập c: "))
if (a == b or c == d):
  print("Hello World!")

if a > b:
  print('Yes')
else:
  print('No')

print("A") if a > b else print("=") if a == b else print("B")

"""Bài 11"""

a = []
b = []
n = int(input("Nhập vào n phần tử: "))
for i in range(n):
  k = int(input(f"Nhập vào phần tử thứ {i + 1}: "))
  a.append(k)

for x in a:
    if x % 2 == 0:
        b.append(x)
print("Mảng a: ", a)
print("Mảng b (chỉ chứa các số chẵn): ", b)

"""Bài 12"""

tong = 0
for number in range(1000):
  if (number % 3 == 0) or (number % 5 == 0):
    tong = tong + number
print("Tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5: ", tong)

Bài 13

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

ketqua = []
min_len = min(len(a), len(b))

for i in range(min_len):
  ketqua.append(a[i] + b[i])

if (len(a) > len(b)):
  ketqua.extend(a[min_len:])
else:
  ketqua.extend(b[min_len:])

ketqua.append(23)
print("Mảng a: ", a)
print("Mảng b: ", b)
print("Mảng kết quả: ", ketqua)

"""Bài 14"""

import numpy as np
m = int(input("Nhập vào m dòng: "))
n = int(input("Nhập vào n cột: "))
a = np.random.rand(m, n) * 100
print(a)

k = int(input("Nhập vào dòng k: "))
print(a[k, :])

k = int(input("Nhập vào cột k: "))
print(a[:, k])

row_sums = np.sum(a, axis=1)
max_sum_index = np.argmax(row_sums)
max_sum = row_sums[max_sum_index]
largest_sum_row = a[max_sum_index, :]

print("Các tổng dòng: ", row_sums)
print("Tổng lớn nhất: ", max_sum)
print("Dòng có tổng lớn nhất: ", largest_sum_row)

tichcot = np.prod(a, axis=0)
index = np.argmin(tichcot)
tichnhonhat = tichcot[index]

print("Tích từng cột: ", tichcot)
print("Cột có tích nhỏ nhất là cột: ", index)
print("Tích nhỏ nhất là: ", tichnhonhat)

phantuchan = []
for i in range(0, a.shape[0], 2):
  for j in range(a.shape[1]):
    val = a[i, j]
    if val % 2 == 0:
      phantuchan.append(val)

if phantuchan:
  tbc = np.mean(phantuchan)
  print("Trung bình cộng: ", tbc)
else:
  print("Không có phần tử chẵn")

tong_bien = 0
dem_bien = 0
for i in range(m):
    for j in range(n):
        if i == 0 or i == m - 1 or j == 0 or j == n - 1:
            tong_bien += a[i, j]
            dem_bien += 1
if dem_bien > 0:
    print("Trung bình cộng các phần tử biên: ", tong_bien / dem_bien)

tich_trong = 1
dem_trong = 0
for i in range(1, m - 1):
    for j in range(1, n - 1):
        tich_trong *= a[i, j]
        dem_trong += 1
if dem_trong > 0:
    print("Trung bình tích các phần tử không thuộc biên: ", tich_trong ** (1/dem_trong))
else:
    print("Không có phần tử nằm bên trong biên.")

Bài 15

import datetime
class SinhVien:
    def __init__(self, masv: str, ten: str, namsinh: int, diemtrungbinh: float):
        self.dssv = []
        self.masv = masv if len(masv) == 10 else "N/A"
        self.ten = ten if len(ten) <= 20 else "N/A"
        self.namsinh = namsinh
        self.diemtrungbinh = diemtrungbinh

    def __str__(self):
        return f"{self.masv} | {self.ten} | {self.namsinh} | {self.diemtrungbinh}"

    def nhapmang(self):
        n = int(input("Nhập vào n sinh viên: "))
        for i in range(n):
          print(f"Nhập thông tin cho sinh viên thứ {i + 1}")
          ms = input("Nhập mã số sinh viên: ")
          t = input("Nhập tên sinh viên: ")
          ns = int(input("Nhập năm sinh của sinh viên: "))
          dtb = float(input("Nhập điểm trung bình: "))
          sv = SinhVien(ms, t, ns, dtb)
          self.dssv.append(sv)

    def kiemtra_sinhvienlenlop(self):
        soluong_sinhvienlenlop = 0
        for sv in self.dssv:
          if sv.diemtrungbinh >= 5:
            soluong_sinhvienlenlop += 1
        return soluong_sinhvienlenlop

    def xuat_cacsinhviendu20tuoi(self):
      soluong_sinhviendu20tuoi = 0
      for sv in self.dssv:
        if (datetime.datetime.now().year - sv.namsinh) >= 20:
          soluong_sinhviendu20tuoi += 1
      print("Số lượng sinh viên đủ 20 tuổi", soluong_sinhviendu20tuoi)

    def dem_sosinhvien_hocdaihoc(self):
      dem = 0
      for sv in self.dssv:
        if (sv.masv[2:2] == "DH"):
          dem += 1
      return dem

    def sosinhvien_coten_Lan(self):
      sosinhvien = 0
      for sv in self.dssv:
        if "Lan" in sv.ten:
          sosinhvien += 1
      return sosinhvien

    def sosinhvien_coho_Phan(self):
      sosinhvien = 0
      for sv in self.dssv:
        if sv.ten.startswith("Phan"):
          sosinhvien += 1
      return sosinhvien

quan_ly = SinhVien("", "", 0, 0.0)
quan_ly.nhapmang()
quan_ly.xuat_cacsinhviendu20tuoi()
soluong_sinhvienlenlop = quan_ly.kiemtra_sinhvienlenlop()
print("Số lượng sinh viên lên lớp: ", soluong_sinhvienlenlop)
soluong_sinhvienhocdaihoc = quan_ly.dem_sosinhvien_hocdaihoc()
print("Số lượng sinh viên học đại học: ", soluong_sinhvienhocdaihoc)
sosinhvien_coten_Lan = quan_ly.sosinhvien_coten_Lan()
print("Số lượng sinh viên có tên Lan", sosinhvien_coten_Lan)
sosinhvien_coho_Phan = quan_ly.sosinhvien_coho_Phan()
print("Số lượng sinh viên có họ Phan", sosinhvien_coho_Phan)

"""**Bài 1**"""

a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
ketqua = []

len_a = len(a)
len_b = len(b)
min_len = min(len_a, len_b)
if (len_b > len_a):
  for i in range(len_a):
    if (b[i] < a[i]):
      ketqua.append(b[i])
    else:
      ketqua.append(a[i])
else:
  for i in range(len_b):
    if (b[i] < a[i]):
      ketqua.append(b[i])
    else:
      ketqua.append(a[i])

if (len_b > len_a):
  ketqua.extend(b[min_len:])
elif (len_a > len_b):
  ketqua.extend(a[min_len:])
print(ketqua)

"""Bài 2"""